spring.application.name=api-transportes

#Configuración con PostgreSQL
spring.datasource.url: ${SPRING_DATASOURCE_URL}
spring.datasource.username: ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD}

#Hibernate
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: false

#Flyway
spring.flyway.enabled: true

server.port: ${SERVER_PORT:8082}

services.driver.url: ${DRIVER_SERVICE_URL:http://localhost:8081}

storage.location: ${STORAGE_LOCATION:uploads}

jwt.secret:${JWT_SECRET}

jwt.expiration:${JWT_EXPIRATION}

app.security.username: ${APP_USERNAME:admin}

app.security.password: ${APP_PASSWORD}