spring.application.name=driver-service

#Configuración con PostgreSQL
spring.datasource.url: ${SPRING_DATASOURCE_URL}
spring.datasource.username: ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD}

#Hibernate
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: false

#Flyway
spring.flyway.enabled: true

server.port: ${SERVER_PORT:8081}

jwt.secret: ${JWT_SECRET}